### ISSUE TITLE
P4jNetworkError running provided PythonAI VS PythonAI (FTG4.40) 

### ISSUE THREAD

**Issue by Danielhp95** [TeamFightingICE/FightingICE#2]
Hello FightingICE developers! And thank you for making fighting game AI research possible. I am really grateful!

I wanted to run the script in [`python/Main_PyAIvsPyAI.py`](https://github.com/TeamFightingICE/FightingICE/blob/master/python/Main_PyAIvsPyAI.py) to make sure that I can successfully run FTG4.4 on my machine. 

Upon running it, I get the following error:

**Command**: `python Main_PyAIvsPyAI.py`

**Output**:

``` python
Traceback (most recent call last):
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 827, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 963, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main_PyAIvsPyAI.py", line 43, in <module>
    main_process()
  File "Main_PyAIvsPyAI.py", line 34, in main_process
    start_game()
  File "Main_PyAIvsPyAI.py", line 15, in start_game
    manager.registerAI(p1.__class__.__name__, p1)
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 1131, in __call__
    answer = self.gateway_client.send_command(command)
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 881, in send_command
    connection = self._get_connection()
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 829, in _get_connection
    connection = self._create_connection()
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 835, in _create_connection
    connection.start()
  File "/home/sarios/Projects/fightingICE-self-play/FightingICE/python/py4j/java_gateway.py", line 970, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:4242)
```

**NOTE**: I get exactly the same error when running the similar script [`python Main_PyAIvsJavaAI.py`](https://github.com/TeamFightingICE/FightingICE/blob/master/python/Main_PyAIvsJavaAI.py)

**Extra information**:

My Java version:
**Command**: `java -version`:
**Output**:
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

My Python version:
**Command**: `python --version`:
**Output**:
```
Python 3.6.6
```

My issue is: **How can I run this test script ([`python/Main_PyAIvsPyAI.py`](https://github.com/TeamFightingICE/FightingICE/blob/master/python/Main_PyAIvsPyAI.py)) to successfully launch the game and have `KickAI` and `DisplayInfo` fight against one another**?

I am planning to use FightingICE (and the [gym-FightingICE](https://github.com/TeamFightingICE/Gym-FightingICE) library) for my upcoming research paper, So I would really value your help in this matter!

**Comment by TeamFightingICE** [comment]
Sorry for my late reply.

First step:
download and unzip the FightingICE from following url
http://www.ice.ci.ritsumei.ac.jp/~ftgaic/Downloadfiles/FTG4.40.zip

Second step:
run the following 2 commands
1)
$cd FTG4.40
2)
in case of linux:
$java -cp FTG4.40.jar:./lib/lwjgl/*:./lib/natives/linux/*:./lib/*  Main --py4j

in case of mac:
$ java -XstartOnFirstThread -cp FTG4.40.jar:./lib/lwjgl/*:./lib/natives/macos/*:./lib/*  Main --py4j

in case of windows:
$ java -cp FTG4.40.jar;./lib/lwjgl/*;./lib/natives/windows/*;./lib/*  Main --py4j

Third step:
open a new terminal and run the following command
$python3 Main_PyAIvsPyAI.py
