### ISSUE TITLE
Exception AbstractMethodError

### ISSUE THREAD

**Issue by PJM9991** [TeamFightingICE/FightingICE#38]
We tried running the game with the SampleAI(KickAI). We loaded the KickAI into the following folder.
/DareFightingICE-6.0.2/data/ai

The Kicking AI Code was taken out of the source code folder from the official TeamFightingICE Github, but it shows the following exception. 

Exception in thread "main" java.lang.AbstractMethodError: Receiver class KickAI does not define or inherit an implementation of the resolved method 'abstract int initialize(struct.GameData, boolean)' of interface aiinterface.AIInterface.
	at aiinterface.AIController.initialize(AIController.java:110)
	at manager.InputManager.startAI(InputManager.java:251)
	at gamescene.Play.initialize(Play.java:157)
	at manager.GameManager.update(GameManager.java:61)
	at manager.DisplayManager.gameLoop(DisplayManager.java:200)
	at manager.DisplayManager.start(DisplayManager.java:87)
	at Main.main(Main.java:22)

Running the game with the (included) MctsAi23i.java  AI works fine, however. 

 The same happens if we create a new Empty AI that implements the methods but does nothing else and export it, as shown in the tutorial to the folder /DareFightingICE-6.0.2/data/ai. What is the problem?

**Comment by DrinkingWater64** [comment]
I am facing the same error here. I understand what is causing this. The KickAI implements `abstract void initialize(struct.GameData, boolean)`
but it asking for implementation of `abstract int initialize(struct.GameData, boolean)`
The MctsAi23 implements the function which returns int. The AIToolKit.jar from the sampleAI has the method returning void. This is what is most probably causing the error.
In this [Repo](https://github.com/TeamFightingICE/FightingICE) they are implementing `abstract int initialize(struct.GameData, boolean)`

How to fix this issue? I am stuck here.
