### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TimZF** [TeamFightingICE/FightingICE#4]
When i try to use the gym env "FightingiceDataNoFrameskip-v0".
It just stops while the screen is saying "Now loading .."
Python runs until line 
obs = self.pipe.recv()
in the reset method 

When i save the output of the stderr/stdout into an file i get the following error.

Oct 27, 2019 3:57:46 PM manager.InputManager <init>
INFORMATION: Create instance: manager.InputManager
Oct 27, 2019 3:57:46 PM manager.DisplayManager initialize
INFORMATION: Create Window 960x640
Oct 27, 2019 3:57:46 PM manager.GraphicManager <init>
INFORMATION: Create instance: manager.GraphicManager
Oct 27, 2019 3:57:46 PM loader.ResourceLoader <init>
INFORMATION: Create instance: loader.ResourceLoader
Python
Oct 27, 2019 3:57:48 PM gamescene.Launcher update
INFORMATION: Transition to PLAY
Oct 27, 2019 3:57:48 PM loader.ResourceLoader loadResource
INFORMATION: Loading the resources
Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.sort(Arrays.java:1438)
	at loader.ResourceLoader.sortByFileName(ResourceLoader.java:571)
	at loader.ResourceLoader.loadImages(ResourceLoader.java:462)
	at loader.ResourceLoader.loadResource(ResourceLoader.java:84)
	at gamescene.Launcher.update(Launcher.java:89)
	at manager.GameManager.update(GameManager.java:65)
	at manager.DisplayManager.gameLoop(DisplayManager.java:166)
	at manager.DisplayManager.start(DisplayManager.java:53)
	at Main.main(Main.java:22)

**Comment by stante** [comment]
I ran into the same problem. The only thing that helped was to start my python program from within the FTG directory.
